package application.model;

import java.util.Objects;

/**
 * Represents a student entity in the student management system.
 *
 * <p>This class stores student information including a generated
 * registration identifier, roll number, name, standard, and division.</p>
 *
 * <p>This class acts as a data application.model and does not contain validation
 * or business logic. Validation is handled by the application.service layer.</p>
 *
 * @author Vincent Silveira
 * @version 1.0
 */
public class Student {

    /**
     * Unique generated identifier for the student.
     *
     * <p>The value is generated by the application and stored as a String.</p>
     */
    private String registrationId;

    /**
     * Student roll number.
     */
    private int rollNo;

    /**
     * Student name.
     */
    private String name;

    /**
     * Student standard/class level.
     */
    private int standard;

    /**
     * Student division.
     */
    private char division;

    /**
     * Creates an empty student object.
     */
    public Student() {}

    /**
     * Creates a student with all fields initialized.
     *
     * @param registrationId unique student identifier
     * @param rollNo student roll number
     * @param name student name
     * @param standard student class level
     * @param division student division
     */
    public Student(
            String registrationId,
            int rollNo,
            String name,
            int standard,
            char division
    ) {
        this.registrationId = registrationId;
        this.rollNo = rollNo;
        this.name = name;
        this.standard = standard;
        this.division = division;
    }

    /**
     * Returns the student's registration identifier.
     *
     * @return registration identifier
     */
    public String getRegistrationId() {
        return registrationId;
    }

    /**
     * Updates the student's registration identifier.
     *
     * @param registrationId new registration identifier
     */
    public void setRegistrationId(String registrationId) {
        this.registrationId = registrationId;
    }

    /**
     * Returns the student's roll number.
     *
     * @return student roll number
     */
    public int getRollNo() {
        return rollNo;
    }

    /**
     * Updates the student's roll number.
     *
     * @param rollNo new student roll number
     */
    public void setRollNo(int rollNo) {
        this.rollNo = rollNo;
    }

    /**
     * Returns the student's name.
     *
     * @return student name
     */
    public String getName() {
        return name;
    }

    /**
     * Updates the student's name.
     *
     * @param name new student name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the student's standard/class level.
     *
     * @return student standard
     */
    public int getStandard() {
        return standard;
    }

    /**
     * Updates the student's standard/class level.
     *
     * @param standard new student standard
     */
    public void setStandard(int standard) {
        this.standard = standard;
    }

    /**
     * Returns the student's division.
     *
     * @return student division
     */
    public char getDivision() {
        return division;
    }

    /**
     * Updates the student's division.
     *
     * @param division new student division
     */
    public void setDivision(char division) {
        this.division = division;
    }

    /**
     * Compares students based on their registration identifier.
     *
     * @param o object to compare
     * @return true if both students have the same registration ID
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;

        if (!(o instanceof Student student))
            return false;

        return Objects.equals(
                registrationId,
                student.registrationId
        );
    }

    /**
     * Generates a hash value based on the student's registration ID.
     *
     * <p>This allows Student objects to be used correctly in
     * collections such as HashSet and HashMap.</p>
     *
     * @return hash value of the student
     */
    @Override
    public int hashCode() {
        return Objects.hash(registrationId);
    }

    /**
     * Returns a readable string representation of this student.
     *
     * <p>Used mainly for debugging and displaying student details.</p>
     *
     * @return formatted student information
     */
    @Override
    public String toString() {
        return "Student{" +
                "registrationId=" + registrationId +
                ", rollNo=" + rollNo +
                ", name='" + name + '\'' +
                ", standard=" + standard +
                ", division=" + division +
                '}';
    }
}
